import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module.js";
import { ApiExceptionFilter } from "./presentation/http.js";
import { RequestObservabilityInterceptor } from "./presentation/observability.interceptor.js";
const app = await NestFactory.create(AppModule, { bufferLogs: true });
app.useGlobalFilters(new ApiExceptionFilter());
app.useGlobalInterceptors(app.get(RequestObservabilityInterceptor));
app.enableShutdownHooks();
await app.listen(Number(process.env.SERVICE_PORT ?? 3008), "0.0.0.0");
